<?php
$gameNewArr = [
        [
            "tipo"=>"2",
            "posicao"=>"a1",
            "situacao"=>""
        ],
        [
            "tipo"=>"3",
            "posicao"=>"b1",
            "situacao"=>""
        ],
        [
            "tipo"=>"4",
            "posicao"=>"c1",
            "situacao"=>""
        ]
        ,
        [
            "tipo"=>"5",
            "posicao"=>"d1",
            "situacao"=>""
        ],
        [
            "tipo"=>"6",
            "posicao"=>"e1",
            "situacao"=>""
        ],
        [
            "tipo"=>"4",
            "posicao"=>"f1",
            "situacao"=>""
        ],
        [
            "tipo"=>"3",
            "posicao"=>"g1",
            "situacao"=>""
        ],
        [
            "tipo"=>"2",
            "posicao"=>"h1",
            "situacao"=>""
        ],
        //----
        [
            "tipo"=>"1",
            "posicao"=>"a2",
            "situacao"=>""
        ],
        [
            "tipo"=>"1",
            "posicao"=>"b2",
            "situacao"=>""
        ],
        [
            "tipo"=>"1",
            "posicao"=>"c2",
            "situacao"=>""
        ]
        ,
        [
            "tipo"=>"1",
            "posicao"=>"d2",
            "situacao"=>""
        ],
        [
            "tipo"=>"1",
            "posicao"=>"e2",
            "situacao"=>""
        ],
        [
            "tipo"=>"1",
            "posicao"=>"f2",
            "situacao"=>""
        ],
        [
            "tipo"=>"1",
            "posicao"=>"g2",
            "situacao"=>""
        ],
        [
            "tipo"=>"1",
            "posicao"=>"h2",
            "situacao"=>""
        ],
        //´pretos
        [
            "tipo"=>"8",
            "posicao"=>"a8",
            "situacao"=>""
        ],
        [
            "tipo"=>"9",
            "posicao"=>"b8",
            "situacao"=>""
        ],
        [
            "tipo"=>"10",
            "posicao"=>"c8",
            "situacao"=>""
        ]
        ,
        [
            "tipo"=>"11",
            "posicao"=>"d8",
            "situacao"=>""
        ],
        [
            "tipo"=>"12",
            "posicao"=>"e8",
            "situacao"=>""
        ],
        [
            "tipo"=>"10",
            "posicao"=>"f8",
            "situacao"=>""
        ],
        [
            "tipo"=>"9",
            "posicao"=>"g8",
            "situacao"=>""
        ],
        [
            "tipo"=>"8",
            "posicao"=>"h8",
            "situacao"=>""
        ],
        //----
        [
            "tipo"=>"7",
            "posicao"=>"a7",
            "situacao"=>""
        ],
        [
            "tipo"=>"7",
            "posicao"=>"b7",
            "situacao"=>""
        ],
        [
            "tipo"=>"7",
            "posicao"=>"c7",
            "situacao"=>""
        ]
        ,
        [
            "tipo"=>"7",
            "posicao"=>"d7",
            "situacao"=>""
        ],
        [
            "tipo"=>"7",
            "posicao"=>"e7",
            "situacao"=>""
        ],
        [
            "tipo"=>"7",
            "posicao"=>"f7",
            "situacao"=>""
        ],
        [
            "tipo"=>"7",
            "posicao"=>"g7",
            "situacao"=>""
        ],
        [
            "tipo"=>"7",
            "posicao"=>"h7",
            "situacao"=>""
        ]

];
